### ISSUE TITLE
mask.py reports success on failure

### ISSUE THREAD

**Issue by dakriy** [ASWWU-Web/python_server#124]
route_handlers/mask.py on line 256 does not check the return of `mask.add_or_update(profile)` and will always return success. The function returns None on failure, and should be checked instead of always assuming it worked and returning success when it obviously didn't succeed.

**Comment by stephenermshar** [comment]
Thanks @dakriy, this is probably something we won't plan on fixing since it's not a security vulnerability, it doesn't appear to be breaking anything at the moment (let us know if you see something it is causing to break), and we're in the process of migrating to Django. 

I'm adding it to the Django Migration project board so we make sure to keep it in mind as we design the new server backend.
